### ISSUE TITLE
AOP-25 | join an online game

### ISSUE THREAD

**Issue by KlnSdr** [KlnSdr/AOP_SoSe23#25]
- depends on:
  - #37 
  - #11 
  - #12 
- based on the ui implement the process for joining a game
- send the appropriate request to the provided server
- make sure to handle a connection failure
### review
- [ ] requirements per ticket definition are met or a reason was stated if they were only partially met
- [ ] code style was adhered to
- [ ] feature branche is rebased

**Comment by sbstnschkhn** [comment]
Dear Mr. Schneider,
I could join the game via Online Spiel beitreten 
LG Sebastian
