### ISSUE TITLE
AOP-28 | update remote game state

### ISSUE THREAD

**Issue by KlnSdr** [KlnSdr/AOP_SoSe23#28]
- whan a tile is clicked send a appropriate request to the server indicating that the tile at (X, Y) was shot on
### review
- [ ] requirements per ticket definition are met or a reason was stated if they were only partially met
- [ ] code style was adhered to
- [ ] feature branche is rebased

**Comment by KlnSdr** [comment]
- when a button is pressed on the opponents board a request is send to /fireAt with the given coordinates as body content

**Comment by sbstnschkhn** [comment]
You know
