### ISSUE TITLE
AOP-29 | submit placed ships

### ISSUE THREAD

**Issue by KlnSdr** [KlnSdr/AOP_SoSe23#29]
- after a player has finished placing its ships send a request to the server persisting the boards state
### review
- [ ] requirements per ticket definition are met or a reason was stated if they were only partially met
- [ ] code style was adhered to
- [ ] feature branche is rebased

**Comment by KlnSdr** [comment]
- the function throws no exceptions -> can be removed
- gameId doesn't have to be a uuid -> no need to convert from string2uuid
- coordinates are submitted using the wrong format
  - format is: `x0,y0|x1,y1|...|xn,yn` not `[(x1, y1),(x2, y1),...]`
- **fix together tomorrow in call**

**Comment by sbstnschkhn** [comment]
Dear Mr Schneider,
I don't know what I was doing yesterday. I was confused. We did talk about the format but I didn't apply it. Now I fixed it 
with best regards Sebastian

**Comment by KlnSdr** [comment]
- review through "pair"-programming -> merge ok
