### ISSUE TITLE
AOP-44 | create new online game

### ISSUE THREAD

**Issue by KlnSdr** [KlnSdr/AOP_SoSe23#44]
- depends on:
  - #37 
  - #11 
  - #12 
- based on the ui implement the process for creating an online game
- send the appropriate request to the provided server
- make sure to handle a connection failure
### review
- [ ] requirements per ticket definition are met or a reason was stated if they were only partially met
- [ ] code style was adhered to
- [ ] feature branche is rebased

**Comment by KlnSdr** [comment]
- view to create new online game now extends view to join online game as the functionality is basically the same

**Comment by sbstnschkhn** [comment]
Dear Mr, Schneider,
I checked it out with yo. so u know
LG Sebastian
