### ISSUE TITLE
AOP-51 | get remote game state

### ISSUE THREAD

**Issue by KlnSdr** [KlnSdr/AOP_SoSe23#51]
- retrieve the gameboard in regular intervals
- depends on: #23

**Comment by KlnSdr** [comment]
- player don't shoot on their own board anymore
- mainscreen checks gameboards in regular intervals (2 s)

**Comment by KlnSdr** [comment]
coloring buttons has to be done after #23 is merged

**Comment by sbstnschkhn** [comment]
Dear Mr Schneider,
Ich konnte kein lokales Spiel erstellen. Da hat es mir eine NullPointerException geworfen. Ansonsten hat es im Online-Game alles funktioniert 
LG Sebastian
